#!/bin/sh

SCRIPT_PATH=`readlink -f $0`
SCRIPT_ROOT=`dirname $SCRIPT_PATH`
PROJ_ROOT=`dirname $SCRIPT_ROOT`

SCRIPT_PATH=$SCRIPT_ROOT/less/bin/lessc

if which node >/dev/null 2>&1; then
    node $SCRIPT_PATH $*;
elif which nodejs >/dev/null 2>&1; then
    nodejs $SCRIPT_PATH $*
else
    echo "Please install nodejs" >&2
    exit 1
fi;
