#!/bin/sh

SCRIPT_PATH=`readlink -f $0`
SCRIPT_ROOT=`dirname $SCRIPT_PATH`
PROJ_ROOT=`dirname $SCRIPT_ROOT`

SCRIPT_PATH=$SCRIPT_ROOT/less/bin/lessc

/usr/bin/env nodejs $SCRIPT_PATH || /usr/bin/env node $SCRIPT_PATH
